# Generated by Django 2.1.4 on 2020-04-03 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, help_text='Link to deal', null=True)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price after Deal', max_digits=6, null=True)),
                ('crossed_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price before Deal', max_digits=6, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, help_text='Degree starting date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Degree ending deadline', null=True)),
                ('slug', models.SlugField(allow_unicode=True, help_text='a user friendly url', max_length=60, unique=True, verbose_name='user friendly url')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Used on the certificate as issuing date', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Deals',
                'ordering': ['-created_at'],
            },
        ),
    ]
