# Generated by Django 2.1.5 on 2020-04-04 01:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='user',
        ),
        migrations.AlterField(
            model_name='deal',
            name='thumbnail',
            field=models.ImageField(upload_to=core.models.path),
        ),
    ]
