# Generated by Django 2.1.5 on 2020-04-05 15:58

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_deal_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(null=True, upload_to=core.models.path)),
                ('description', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='deal',
            options={},
        ),
        migrations.RemoveField(
            model_name='deal',
            name='slug',
        ),
        migrations.AlterField(
            model_name='deal',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=core.models.path),
        ),
        migrations.AlterModelTable(
            name='deal',
            table=None,
        ),
        migrations.AddField(
            model_name='deal',
            name='category',
            field=models.ManyToManyField(related_name='deals', to='core.Category'),
        ),
        migrations.AddField(
            model_name='deal',
            name='location',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='core.Location'),
        ),
    ]
