# Generated by Django 2.1.5 on 2020-04-05 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200405_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='location',
        ),
    ]
