# Generated by Django 2.1.5 on 2020-04-05 20:21

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200405_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Location'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.path),
        ),
    ]
