# Generated by Django 2.1.5 on 2020-04-05 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200405_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='deals', to='core.Category'),
        ),
    ]
