# Generated by Django 2.1.5 on 2020-04-15 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200412_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='category',
        ),
        migrations.AddField(
            model_name='deal',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='core.Category'),
        ),
    ]
